### PR TITLE
Enable tests and lint

### PR DESCRIPTION
**Pull request by mmcfarland**
### Overview
Fixes lint and test errors for JS and Django/Python and re-enables those checks from `./scripts/test.sh to use from CI`

### Notes
Didn't address the JS unit tests in this PR and that section remains commented out.

Connects #28 
Connects #45 

### Testing
* Run `./scripts/test.sh` and verify it does not report lint or test errors
* Rebundle client and vendor packages and verify the app still runs

### CODE REVIEW

**Comment by rajadain** [comment]
Heads up, there are some merge conflicts. Will take a look once they're resolved.

**Comment by mmcfarland** [comment]
@azavea-bot rebuild

Updated.

**Comment by rajadain** [comment]
Seeing some flake8 failures in the latest build:

```
+ vagrant ssh app -c 'flake8 /opt/app/pollinator --exclude build || echo flake8 check failed'
/opt/app/pollinator/src/pollinator/crop_yield.py:24:16: E201 whitespace after '{'
/opt/app/pollinator/src/pollinator/crop_yield.py:24:71: E202 whitespace before '}'
/opt/app/pollinator/src/pollinator/crop_yield.py:26:1: E302 expected 2 blank lines, found 1
/opt/app/pollinator/src/pollinator/crop_yield.py:152:80: E501 line too long (88 > 79 characters)
/opt/app/pollinator/src/pollinator/reclass/write_crop_type_json.py:7:1: E302 expected 2 blank lines, found 1
/opt/app/pollinator/src/pollinator/reclass/write_crop_type_json.py:21:17: E128 continuation line under-indented for visual indent
/opt/app/pollinator/tests/tests.py:117:80: E501 line too long (88 > 79 characters)
/opt/app/pollinator/tests/tests.py:119:80: E501 line too long (81 > 79 characters)
/opt/app/pollinator/tests/tests.py:129:80: E501 line too long (83 > 79 characters)
flake8 check failed
```

**Comment by mmcfarland** [comment]
Yikes.  I can't keep up with all this lint that keeps making it into `develop` while this PR is open!  I'll rebase and fix the new warning.

**Comment by mmcfarland** [comment]
Fixed the new lint in 0f0e8101f89093d069c63421e738f648d6402a9e and rebased on `develop`

@azavea-bot rebuild

**Pull request merged**
