### PR TITLE
Implement Logging Out

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Implements logging out.

Connects #335 

## Testing Instructions

* Check out this branch and `beekeepers start`
* Go to [:8000/?beekeepers](http://localhost:8000/?beekeepers) and log in. Ensure you see a ▾ icon next to the username.
* Hover on the username. Ensure you see a dropdown with a "Log Out" button.
* Ensure hovering on the username, or the Log Out button, keeps the dropdown open and it doesn't accidentally close.
* Click the "Log Out" button. Ensure you are logged out and the app resets to its initial state.

### CODE REVIEW

**Comment by fungjj92** [comment]
Add the carrot icon to this list#393

**Comment by rajadain** [comment]
Good point about accessibility. Generally any app that is primarily map driven is going to be a challenge for the visually impaired, so we may have bigger problems, but it's a good habit to make things accessible by default, which we should always try to do. 5ae9b7e includes a hidden button that will be visible to screen readers only, using [recommended styling from 18F](https://accessibility.18f.gov/hidden-content/).

**Comment by fungjj92** [comment]
Great ! Tested on ipad mode on chrome.

**Comment by rajadain** [comment]
Thanks for taking a look!

**Pull request merged**
