### PR TITLE
Skip Analyze

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

After a shape is drawn, and the user clicks "Confirm", they are taken to the modeling view instead of analyze. Analyze is completely removed from the front-end: it no longer exists as its own page or as a tab in the modeling view. The back button in the modeling view has also been removed.

### Demo

bee-transition-to-model

### Notes

The modeling view currently fires TR-55, which was easier than setting up a dummy endpoint.

I've created #32 and #33 for issues discovered, but not addressed, while working on this.

## Testing Instructions

Pull down the branch. Run the bundle script:

```
./scripts/bundle.sh --debug --vendor
```

Load [http://localhost:8000](http://localhost:8000). Draw a shape, and click "Confirm". You should be taken to the modeling view with the correct shape loaded. The actual model may not run (for uninvestigated reasons).

Builds on top of #29 
Connects #23

### CODE REVIEW

**Comment by arottersman** [comment]
Tested, and looks good!

Consider also  removing:
- analyze api endpoints https://github.com/project-icp/bee-pollinator-app/blob/54aa0ca7a93a6e0841fa397646ede7a624ea1a58/src/icp/apps/home/urls.py#L23
- `src/icp/sass/pages/_analyze.scss`

**Comment by rajadain** [comment]
Good point, also removed in the latest push.

**Comment by rajadain** [comment]
Also rebased to remove merge conflicts.

**Comment by arottersman** [comment]
+1!

**Pull request merged**
