### PR TITLE
Data upload docs

### PR DESCRIPTION
**Pull request by mmcfarland**
## Overview

Add documentation for updating beekeeper rasters

Connects #386 

### Notes

The `beekeeper-data` credentials are in LastPass

## Testing Instructions

 * Confirm you can log in with the referenced IAM account, and that the account _only_ has access to the beekeepers raster s3 bucket, and no other services/buckets.
 * Confirm the steps listed in the docs are correct.

### CODE REVIEW

**Comment by rajadain** [comment]
Taking a look now.

**Comment by rajadain** [comment]
When trying to upload a test file following the docs, I just get this message in the AWS UI:

image

with no detail about why it failed. This is the file I'm trying to upload:

**Comment by mmcfarland** [comment]
Thank you for catching that, the UI was not obvious that the error was happening, but I do get the same --- appears to be insufficient privileges for the user.

screenshot from 2019-02-18 11 57 07

**Comment by rajadain** [comment]
I just tried this again. If I don't uncheck "Object Read" and "Object Write" permissions, it works, otherwise it still fails.

**Comment by mmcfarland** [comment]
I updated the docs and screenshot for the step, to include Object Read/Write.

**Pull request merged**
