### PR TITLE
Add Opacity Slider to Crop Layer

### PR DESCRIPTION
**Pull request by arottersman**
## Overview
This PR puts an opacity slider inside the crop layer control when it's on. 

## Notes
- The thin track on this slider makes it difficult to change the opacity by clicking on the track (as opposed to grabbing the thumb circle thing and dragging). I tried increasing its padding, but couldn't get the padding to be clear (it made the track all fat)
- Another possible implementation of this is to always show the slider, set its initial opacity to 0 and remove the eye button...I think @jfrankl is still unsure what's preferable/waiting for user testing?

## Demo
screen shot 2016-12-08 at 1 39 27 pm
screen shot 2016-12-08 at 1 39 33 pm

## Testing Instructions
Pull this branch and `./scripts/bundle.sh`
- Click the eye on the crop layer
- Drag that opacity slider
- Flip the streets/satellite switch
- Toggle the eye

Connects #66

### CODE REVIEW

**Comment by rajadain** [comment]
The buttons are now out of alignment with the ones on the right, and the full-screen icon no longer fits:

image

**Comment by rajadain** [comment]
Worth noting that the slider looks different on different browsers:

image

in Firefox above, for example, the track is easily clickable because its hit area is as tall as the thumb.

**Comment by arottersman** [comment]
I've consolidated the styling between firefox/chrome/ie and fixed that expand control mis-alignment.

The left and right controls are not on the same line on develop as well -- the attribution pushes the right controls up.

**Comment by arottersman** [comment]
Here's what the controls look like lined up.
screen shot 2016-12-08 at 3 31 36 pm

**Comment by rajadain** [comment]
Oh sorry I didn't realize that the left and right controls were unaligned on `develop` as well. Taking another look.

**Comment by arottersman** [comment]
Turned layer off by default and squashed. Going to merge now. Thanks for looking at this!

**Pull request merged**
