### PR TITLE
Style cleanup

### PR DESCRIPTION
**Pull request by jfrankl**
I started doing some minor style cleanup.

image

image

image

### CODE REVIEW

**Comment by ajrobbins** [comment]
@jfrankl Can you post a screenshot of this part of the landing page sidebar? 

screen shot 2017-05-16 at 9 21 16 am

Due to some compromises we made with the client, this is the only place the "Quick start guide" (which actually should be renamed the "Help page") will be called out on the site, and it's an important resource. Can we give it some emphasis via styling?

**Comment by arottersman** [comment]
@ajrobbins Here's screenshot with the whole sidebar. The Quick Start/Help page will still be below the fold on shorter screens.
screen shot 2017-05-16 at 12 56 33 pm

**Comment by arottersman** [comment]
Things look good, but the table got pushed down in model view:
screen shot 2017-05-16 at 1 04 06 pm

**Comment by ajrobbins** [comment]
>The Quick Start/Help page will still be below the fold on shorter screens. The subheader text will be shortened, so it should eventually be above the fold for most screens.

**Comment by ajrobbins** [comment]
The grey text below the header on the landing page, select area, and confirm area pages is kind of low-contrast and hard to read. Can we make it a bit easier?

**Comment by jfrankl** [comment]
@arottersman could you take another look?

I have addressed the following issues:

- Increase text contrast
- Emphasize guide link
- Table getting pushed down

image

**Pull request merged**
