### PR TITLE
Add Splash Page

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Adds a splash view for users to land on, so they can get some context about the application. Once ready, they can click "Get started" to move to the drawing area.

### Demo

image

## Testing Instructions

 * Check out this branch
 * Bundle vendor scripts to include new image:

        ./scripts/bundle.sh --vendor

 * Open the home page [localhost:8000](http://localhost:8000/). You should see the splash screen.
 * Click "Get started". You should be taken to the draw view.
 * Drawing should work as expected.
 * Back / forward buttons should work as expected.
 * You should be able to go directly to the draw view at [localhost:8000/draw](http://localhost:8000/draw)

Connects #47

### CODE REVIEW

**Comment by ajrobbins** [comment]
Has the geolocator been removed from this page?

**Comment by rajadain** [comment]
The geolocator search is only available in the draw view, but taking another look at the wireframes I see it should be available in the splash screen as well. Fixing now.

**Comment by rajadain** [comment]
Done:

image

**Comment by rajadain** [comment]
Thanks for taking a look. Squashed fixups. Merging now ...

**Pull request merged**
