### PR TITLE
Rename MMW -->  ICP/Bee-Pollinator

### PR DESCRIPTION
**Pull request by arottersman**
Changes just about every reference:
- mmw --> icp
- model-my-watershed --> bee-pollinator
- Model My Watershed --> Bee Pollinator

### Testing
- Search for `mmw`, `MMW`, `model-my-watershed`, `Model My Watershed`, `WikiWatershed` and whatever other permutations you can think of in the files, filenames, and directory names. There will be a few hits (a link to a Model My Watershed PR, the staging/production URLs we're not ready to update yet, and the geoprocessing repo)

- Destroy whatever VMs you already have, and rebuild them
- There will be linting errors, but you should still be able to see the stripped down app at `localhost:8000`

Connects #16

### CODE REVIEW

**Comment by rajadain** [comment]
Let's remove this WikiWatershed link https://github.com/project-icp/bee-pollinator-app/blob/feature/arr/change-mmw-to-icp/src/icp/js/src/core/templates/header.html#L5

**Comment by rajadain** [comment]
Were these references not update because we intend to reuse the geoprocessing project?

```
> ag mmw
deployment/ansible/roles/bee-pollinator.base/defaults/main.yml
14:  MMW_GEOPROCESSING_VERSION: "{{ geop_version }}"

deployment/ansible/roles/bee-pollinator.geoprocessing/defaults/main.yml
3:geop_jar_url: "https://github.com/WikiWatershed/mmw-geoprocessing/releases/download/{{ geop_version }}/mmw-geoprocessing-assembly-{{ geop_version }}.jar"

deployment/ansible/roles/bee-pollinator.geoprocessing/tasks/main.yml
8:           dest="{{ geop_home }}/mmw-geoprocessing-{{ geop_version }}.jar"

deployment/ansible/roles/bee-pollinator.spark-jobserver/templates/spark-jobserver.conf.j2
15:    "geoprocessing-{{ geop_version }}" = {{ geop_home }}/mmw-geoprocessing-{{ geop_version }}.jar

deployment/RELEASES.md
80:Within 60 seconds, `app.wikiwatershed.org` and `mmw.azavea.com` should reflect the current release.

src/icp/icp/settings/base.py
354:        'SummaryJob': 'context=geoprocessing&appName=geoprocessing-%s&classPath=org.wikiwatershed.mmw.geoprocessing.SummaryJob' % environ.get('MMW_GEOPROCESSING_VERSION', '0.1.0'),  # NOQA
```

**Comment by arottersman** [comment]
Watershed linked removed- thanks!

**Comment by arottersman** [comment]
Should I strip the geoprocessing stuff with this PR or do you think that's out of scope?

**Comment by rajadain** [comment]
I think it's out of scope. Let's leave it in but not rename it because it's going away soon.

**Comment by rajadain** [comment]
This may have been accidentally included https://github.com/project-icp/bee-pollinator-app/blob/feature/arr/change-mmw-to-icp/deployment/ansible/workers.retry

**Comment by arottersman** [comment]
Oops, I've removed it.

**Comment by rajadain** [comment]
Is there a card for removing the Micro Site? That's the last part. If so, this is good. +1

**Comment by arottersman** [comment]
Just created a card for removing the micro site: https://github.com/project-icp/bee-pollinator-app/issues/18 

Thanks for the review!

**Pull request merged**
