### PR TITLE
Update Styling (Font sizes, Colors)

### PR DESCRIPTION
**Pull request by arottersman**
## Overview
- Update all the branding color variables 
- Increase the font size
- Restyle Search bar
- Restyle drawn shape masks (no border on finished shaped, brand primary while drawing)
- Remove current page title from the app header
- Don't show login modal on start 

@jfrankl -- This is more of a first pass at styling, but let me know if anything stands out for edits in the screenshots below!

- Colors eye-dropped from wireframes:
    #525659 header light
    #464648 header dark
    #ffffff white
    #a4a4a4 disabled font
    #f9cf2f brand primary (the honeycomb yellow)
    #58585a scenario header
    #d0d0d0 active tab scenario
    #b3b3b3 inactive tab scenario
    #608caf active blue

### Login modal
More of a demonstration of the brand-primary at work, and not something that actually looks too good!

screen shot 2016-11-09 at 3 18 42 pm
_Login modal with hover over guest `btn-primary`_
screen shot 2016-11-09 at 3 18 48 pm
_Login modal with hover over little top buttons_
screen shot 2016-11-09 at 3 18 53 pm
_Header and search_
screen shot 2016-11-09 at 3 19 02 pm
_Drawing_
screen shot 2016-11-09 at 3 24 36 pm
screen shot 2016-11-09 at 3 24 21 pm
_Drawn_
screen shot 2016-11-09 at 3 19 23 pm

## Testing Instructions
Pull this branch and rebundle with `./scripts/bundle.sh`

Look at the wireframes and look at the app
- Check colors align
- Check font sizing looks similar
- Check no more current page title in app header
- Check draw polygons look similar

Connects #20

### CODE REVIEW

**Comment by arottersman** [comment]
Looking at the original issue, would like to add that I...
- Didn't change the font family
- Just left header text as "Bee Pollinator" until we've decided on a non-filler name

**Comment by jfrankl** [comment]
Nice looking start. I think this is fine to merge in as a first pass.

Note on color: because the yellow is so vibrant, I am using a subdued blue (#4A8BAD) as a secondary color in the designs. You don't need to worry about it now—I can work on adding it in later.

Here are some screens of it in action:

image

image

**Comment by arottersman** [comment]
Great! I've added (hopefully) that blue as the variable `$active`, which, now that I look at it, isn't really used where I thought it was used....

**Comment by jtarricone** [comment]
Style wise this looks good, but I noticed sidebar top element was wonky -->
20161110_mmw

I don't know if it's worth worrying about since there are already changes in play that will modify that control, it's up to you.

**Pull request merged**
